// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoutesService.API.Data;

#nullable disable

namespace RoutesService.API.Migrations
{
    [DbContext(typeof(RoutesDbContext))]
    [Migration("20250815075438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoutesService.Domain.Entities.Base.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool?>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EkleyenKullaniciId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullaniciId")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullaniciId")
                        .HasColumnType("text");

                    b.Property<bool?>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasDiscriminator().HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.KullaniciRolleri", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("KullaniciId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("KullaniciRolleri");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RolIzinleri", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("IzinId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "IzinId");

                    b.HasIndex("IzinId");

                    b.ToTable("RolIzinleri");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaKategoriAtama", b =>
                {
                    b.Property<int>("RotaId")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.HasKey("RotaId", "KategoriId");

                    b.HasIndex("KategoriId");

                    b.ToTable("RotaKategoriAtama");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Izin", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Izin");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Kullanici", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Kullanici");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.KurumTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("WebSitesi")
                        .HasColumnType("text");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("Ad")
                                .HasColumnName("KurumTanim_Ad");

                            t.Property("Email")
                                .HasColumnName("KurumTanim_Email");

                            t.Property("Telefon")
                                .HasColumnName("KurumTanim_Telefon");
                        });

                    b.HasDiscriminator().HasValue("KurumTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Rol", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("Ad")
                                .HasColumnName("Rol_Ad");
                        });

                    b.HasDiscriminator().HasValue("Rol");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaKategoriTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("Ad")
                                .HasColumnName("RotaKategoriTanim_Ad");
                        });

                    b.HasDiscriminator().HasValue("RotaKategoriTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaOnemliYerTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("AciklamaDetay")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<double?>("Boylam")
                        .HasColumnType("double precision");

                    b.Property<double?>("Enlem")
                        .HasColumnType("double precision");

                    b.Property<int?>("RotaId")
                        .HasColumnType("integer");

                    b.HasIndex("RotaId");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("Ad")
                                .HasColumnName("RotaOnemliYerTanim_Ad");
                        });

                    b.HasDiscriminator().HasValue("RotaOnemliYerTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaResimTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("AciklamaDetay")
                        .HasColumnType("text");

                    b.Property<byte[]>("Resim")
                        .HasColumnType("bytea");

                    b.Property<string>("ResimAdi")
                        .HasColumnType("text");

                    b.Property<long?>("ResimBoyut")
                        .HasColumnType("bigint");

                    b.Property<string>("ResimUzanti")
                        .HasColumnType("text");

                    b.Property<int?>("RotaId")
                        .HasColumnType("integer");

                    b.HasIndex("RotaId");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("AciklamaDetay")
                                .HasColumnName("RotaResimTanim_AciklamaDetay");

                            t.Property("RotaId")
                                .HasColumnName("RotaResimTanim_RotaId");
                        });

                    b.HasDiscriminator().HasValue("RotaResimTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Adi")
                        .HasColumnType("text");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<double?>("Mesafe")
                        .HasColumnType("double precision");

                    b.Property<string>("Renk")
                        .HasColumnType("text");

                    b.Property<int?>("TahminiSureDakika")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("RotaTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaYorumTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int?>("RotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Yorum")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("RotaId");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("RotaId")
                                .HasColumnName("RotaYorumTanim_RotaId");
                        });

                    b.HasDiscriminator().HasValue("RotaYorumTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.YetkiAlaniTanim", b =>
                {
                    b.HasBaseType("RoutesService.Domain.Entities.Base.Entity");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<int?>("KurumId")
                        .HasColumnType("integer");

                    b.HasIndex("KurumId");

                    b.ToTable("Entity", t =>
                        {
                            t.Property("Ad")
                                .HasColumnName("YetkiAlaniTanim_Ad");

                            t.Property("Geometry")
                                .HasColumnName("YetkiAlaniTanim_Geometry");
                        });

                    b.HasDiscriminator().HasValue("YetkiAlaniTanim");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.KullaniciRolleri", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutesService.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RolIzinleri", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.Izin", "Izin")
                        .WithMany("RolIzinleri")
                        .HasForeignKey("IzinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutesService.Domain.Entities.Rol", "Rol")
                        .WithMany("RolIzinleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izin");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaKategoriAtama", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.RotaKategoriTanim", "Kategori")
                        .WithMany("RotaKategoriler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutesService.Domain.Entities.RotaTanim", "Rota")
                        .WithMany("RotaKategoriler")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaOnemliYerTanim", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.RotaTanim", "Rota")
                        .WithMany("OnemliYerler")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaResimTanim", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.RotaTanim", "Rota")
                        .WithMany("Resimler")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaYorumTanim", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("RoutesService.Domain.Entities.RotaTanim", "Rota")
                        .WithMany("Yorumlar")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.YetkiAlaniTanim", b =>
                {
                    b.HasOne("RoutesService.Domain.Entities.KurumTanim", "Kurum")
                        .WithMany("YetkiAlanlari")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Izin", b =>
                {
                    b.Navigation("RolIzinleri");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciRolleri");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.KurumTanim", b =>
                {
                    b.Navigation("YetkiAlanlari");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");

                    b.Navigation("RolIzinleri");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaKategoriTanim", b =>
                {
                    b.Navigation("RotaKategoriler");
                });

            modelBuilder.Entity("RoutesService.Domain.Entities.RotaTanim", b =>
                {
                    b.Navigation("OnemliYerler");

                    b.Navigation("Resimler");

                    b.Navigation("RotaKategoriler");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
